/* UI strings — [Arabic, English]. Game text is fictional. */
CP.addStrings({
  title: ['كمين: وردية ليل', 'CHECKPOINT: NIGHT SHIFT'],
  titleA: ['كمين', 'CHECKPOINT'],
  titleB: ['وردية ليل', 'NIGHT SHIFT'],
  subtitle: ['محاكاة كمين مصري ثنائية الأبعاد', 'An Egyptian checkpoint simulation'],
  credit: ['تطوير: حسام حجازي', 'Developed by Hossam Hegazi'],
  fictionNote: ['كل الأسماء والوثائق والإجراءات في اللعبة خيالية.', 'All names, documents and procedures in this game are fictional.'],
  loading: ['جاري التحميل…', 'Loading…'],
  loadFail: ['تعذر تحميل ملف: {f}', 'Could not load file: {f}'],
  loadFailHelp: ['تأكد إن فولدر assets جنب ملف index.html، أو شغّل اللعبة من سيرفر محلي.', 'Keep the assets folder beside index.html, or run the game from a local web server.'],
  tapToStart: ['اضغط للبدء (لتفعيل الصوت)', 'Tap to start (enables audio)'],

  m_continue: ['كمّل الوردية', 'Continue shift'],
  m_new: ['مسيرة جديدة', 'New career'],
  m_free: ['دورية حرة', 'Free patrol'],
  m_freeLocked: ['تتفتح بعد الوردية التدريبية', 'Unlocks after the training shift'],
  m_settings: ['الإعدادات', 'Settings'],
  m_how: ['طريقة اللعب', 'How to play'],
  m_noSave: ['مفيش وردية محفوظة', 'No saved shift'],
  m_careerOf: ['مسيرة: الوردية {n}', 'Career: shift {n}'],
  m_newConfirm: ['هتبدأ مسيرة جديدة وتمسح الحفظ الحالي. متأكد؟', 'Start a new career and replace the current save?'],

  // HUD
  h_shift: ['الوردية', 'Shift'],
  h_queue: ['الطابور', 'Queue'],
  h_trust: ['ثقة الناس', 'Trust'],
  h_partner: ['الزميل', 'Partner'],
  h_idle: ['متاح', 'Available'],
  h_offscreen: ['+{n} بره الكادر', '+{n} off-screen'],
  h_pause: ['إيقاف', 'Pause'],
  h_notebook: ['النوتة', 'Notebook'],
  h_speedRead: ['الوقت أبطأ أثناء القراءة', 'Time slowed while reading'],
  h_paused: ['متوقف', 'Paused'],
  h_emergency: ['طوارئ — الوقت عادي', 'Emergency — normal speed'],

  // locations
  loc_alex: ['كورنيش إسكندرية — قايتباي', 'Alexandria Corniche — Qaitbay'], loc_alex_d: ['زحمة الكورنيش والتاكسي الإسكندراني وعربيات المينا.', 'Corniche traffic, Alexandria taxis and port vehicles.'],
  loc_sinai: ['طريق دهب الساحلي — جنوب سيناء', 'Dahab coastal road — South Sinai'], loc_sinai_d: ['جبال سيناء والبحر الأحمر؛ سياح وعربيات جاية من شرم ونويبع.', 'Sinai mountains and the Red Sea; tourists and traffic from Sharm and Nuweiba.'],
  loc_hurghada: ['ممشى الغردقة — المارينا', 'Hurghada Marina promenade'], loc_hurghada_d: ['مراكب ومحلات وسياح لحد آخر الليل.', 'Yachts, shops and tourists late into the night.'],
  loc_luxor: ['كورنيش الأقصر — البر الشرقي', 'Luxor Corniche — East Bank'], loc_luxor_d: ['معابد ونيل وأتوبيسات سياحية.', 'Temples, the Nile and tour coaches.'],
  loc_aswan: ['كورنيش أسوان — النوبة', 'Aswan Corniche — Nubia'], loc_aswan_d: ['النيل والجزر والبيوت النوبي.', 'The Nile, islands and Nubian houses.'],
  loc_cairo: ['أطراف القاهرة', 'Cairo outskirts'],
  loc_cairo_d: ['زحمة وطوابير أطول. مدينة، ميكروباصات وتاكسيات.', 'Denser traffic and longer queues. Microbuses and taxis.'],
  loc_desert: ['الطريق الصحراوي', 'Desert highway'],
  loc_desert_d: ['عربيات أقل، مسافات أطول، نقل تقيل وإضاءة ضعيفة.', 'Fewer vehicles, long trips, heavy trucks, poor light.'],

  // vehicle types
  v_classic_sedan: ['ملاكي قديمة', 'Classic sedan'],
  v_pol_traffic_sedan: ['شرطة المرور — سيدان', 'Traffic police sedan'],
  v_pol_sedan: ['عربية شرطة سيدان', 'Police sedan'],
  v_pol_hatch: ['عربية شرطة صغيرة', 'Police hatchback'],
  v_pol_suv: ['عربية شرطة دفع رباعي', 'Police SUV'],
  v_pol_4x4: ['جيب شرطة', 'Police 4×4'],
  v_pol_pickup: ['بوكس الشرطة', 'Police pickup'],
  v_pol_van: ['فان الشرطة', 'Police van'],
  v_pol_hiace: ['ميكروباص الشرطة', 'Police minibus'],
  v_pol_armored: ['مدرعة الشرطة', 'Police armoured truck'],
  v_pol_tow: ['ونش الشرطة', 'Police tow truck'],
  v_silver_sedan: ['ملاكي فضي', 'Silver sedan'],
  v_estate_wagon: ['ستيشن بيج', 'Estate wagon'], v_green_pickup: ['نص نقل أخضر', 'Green pickup'], v_white_luxury: ['ملاكي أبيض فخم', 'White luxury sedan'],
  v_box_truck: ['ربع نقل صندوق', 'Box truck'], v_red_classic: ['نصر ١٢٨ أحمر', 'Red Nasr 128'], v_blue_hatch: ['هاتشباك أزرق', 'Blue hatchback'],
  v_alex_taxi: ['تاكسي إسكندراني', 'Alexandria taxi'], v_maroon_hatch: ['هاتشباك نبيتي', 'Maroon hatchback'],
  v_cairo_taxi: ['تاكسي القاهرة', 'Cairo taxi'],
  v_charcoal_suv: ['عربية دفع رباعي', 'SUV'],
  v_microbus: ['ميكروباص', 'Microbus'],
  v_older_minibus: ['ميني باص قديم', 'Older minibus'],
  v_city_bus: ['أتوبيس نقل عام', 'City bus'],
  v_cargo_truck: ['عربية نقل', 'Cargo truck'],
  v_ambulance: ['إسعاف', 'Ambulance'],
  v_police_pickup: ['بوكس شرطة', 'Police pickup'],
  v_courier_van: ['فان توصيل', 'Courier van'],
  v_coach: ['أتوبيس سياحي', 'Coach'],
  cls_private: ['ملاكي', 'Private'],
  cls_taxi: ['أجرة', 'Taxi'],
  cls_passenger: ['نقل ركاب', 'Passenger transport'],
  cls_cargo: ['نقل', 'Cargo'],
  cls_service: ['خدمة', 'Service'],
  lic_private: ['خاصة', 'Private'],
  lic_pro: ['مهنية', 'Professional'],

  // dock / card
  c_select: ['اختار عربية من الطابور', 'Select a vehicle in the queue'],
  c_selectHelp: ['اضغط على عربية، أو استخدم Q/E للتنقل. العربية اللي عند العلامة مستنية قرارك.', 'Tap a vehicle or use Q/E to cycle. The vehicle at the marker is waiting for your decision.'],
  c_plate: ['اللوحة', 'Plate'],
  c_pax: ['ركاب', 'passengers'],
  c_wait: ['انتظار', 'Waiting'],
  c_status: ['الحالة', 'Status'],
  c_notice: ['ملاحظة', 'You notice'],
  c_plateUnreadable: ['اللوحة مش واضحة من بعيد', 'Plate not readable from here'],
  st_approach: ['جاية', 'Approaching'],
  st_queue: ['في الطابور', 'In queue'],
  st_marker: ['عند علامة الوقوف', 'At the stop marker'],
  st_stopped: ['موقوفة للفحص', 'Stopped for a check'],
  st_toBay: ['رايحة ساحة الفحص', 'Moving to bay'],
  st_bay: ['في ساحة الفحص', 'In inspection bay'],
  st_leaving: ['ماشية', 'Leaving'],
  st_held: ['متحفظ عليها', 'Held'],
  st_closed: ['القضية اتقفلت', 'Case closed'],

  // actions
  a_stop: ['فحص', 'Inspect'],
  a_stop_s: ['ابدأ فحص العربية', 'Start checking this car'],
  a_wave: ['عدّي', 'Wave through'],
  a_wave_s: ['افتح البوابة', 'Open gate, let pass'],
  a_approach: ['كلّم السواق', 'Talk to the driver'], a_approach_f: ['كلّم السواقة', 'Talk to the driver'],
  a_approach_s: ['روح للشباك واتكلم', 'Walk to the window and talk'],
  a_talk: ['الحوار', 'Conversation'],
  a_talk_s: ['افتح الحوار تاني', 'Reopen the conversation'],
  a_docs: ['الأوراق', 'Documents'],
  a_docs_req: ['اطلب الرخص', 'Request documents'],
  a_docs_s: ['قارن الرخص', 'Compare papers'],
  a_bay: ['ساحة الفحص', 'Inspection bay'],
  a_bay_s: ['حوّل العربية للساحة', 'Divert the vehicle'],
  a_inspect: ['تفتيش', 'Search vehicle'],
  a_inspect_s: ['افحص أماكن محددة', 'Search chosen areas'],
  a_screen: ['كشف', 'Screening'],
  a_screen_s: ['نفس أو مخدرات', 'Breath or drug test'],
  a_radio: ['اللاسلكي', 'Radio verify'],
  a_radio_s: ['استعلام من العمليات', 'Query dispatcher'],
  a_partner: ['الزميل', 'Ask partner'],
  a_partner_s: ['كلّفه بمهمة', 'Assign a task'],
  a_record: ['تسجيل', 'Record'],
  a_record_s: ['سجّل ملاحظة', 'Log an observation'],
  a_resolve: ['قرار', 'Resolve case'],
  a_resolve_s: ['اقفل القضية بسبب', 'Decide with reasons'],
  a_return: ['رجّع الأوراق', 'Return documents'],
  a_release: ['اطلق العربية', 'Release vehicle'],
  a_gate: ['البوابة', 'Gate'],
  a_prio: ['حارة الطوارئ', 'Priority lane'],
  a_prioOpen: ['افتح حارة الطوارئ', 'Open priority lane'],
  a_prioClose: ['اقفل حارة الطوارئ', 'Close priority lane'],
  a_flow: ['وضع المرور', 'Traffic mode'],
  a_flowHold: ['وقوف إجباري', 'Stop every vehicle'],
  a_flowFlow: ['مرور هادي', 'Slow flow'],
  a_visitor: ['كلّم الزائر', 'Help visitor'],
  a_manualGate: ['رفع البوابة يدوي', 'Manual gate override'],
  a_repairGate: ['صلّح موتور البوابة', 'Repair gate motor'],
  a_generator: ['شغّل المولد', 'Restart generator'],
  a_assistVehicle: ['ساعد العربية', 'Assist vehicle'],
  a_incident: ['حل الخلاف', 'Handle incident'],
  a_walkTo: ['امشي هناك', 'Walk there'],

  // unavailability reasons
  r_noVehicle: ['مفيش عربية مختارة', 'No vehicle selected'],
  r_notAtMarker: ['لازم العربية تبقى عند علامة الوقوف', 'Vehicle must be at the stop marker'],
  r_alreadyStopped: ['الفحص بدأ بالفعل', 'Check already started'],
  r_needStop: ['اضغط «فحص» الأول', 'Press “Inspect” first'],
  r_caseOpen: ['القضية لسه مفتوحة — اتخذ قرار الأول', 'Case still open — resolve it first'],
  r_needDocs: ['اطلب الرخص من السواق الأول — لازم يسلّمها لك علشان تشوفها', 'Ask the driver for the documents first — you can only read them once handed over'], r_docsHanding: ['السواق بيطلّع الرخص…', 'The driver is handing over the papers…'], docs_handed: ['السواق سلّمك الرخص — افتح «الأوراق»', 'The driver handed you the papers — open “Documents”'], docs_handed_f: ['السواقة سلّمتك الرخص — افتح «الأوراق»', 'The driver handed you the papers — open “Documents”'],
  r_needBay: ['لازم العربية تكون في ساحة الفحص', 'Vehicle must be in the inspection bay'],
  r_bayFull: ['الساحة مشغولة', 'Inspection bay is full'],
  r_tooLong: ['العربية أطول من الساحة (أقصى ٧ متر)', 'Vehicle too long for the bay (max 7 m)'],
  r_gateJam: ['موتور البوابة عطلان', 'Gate motor is jammed'],
  r_tooClose: ['قريبة جداً — مش هتلحق تقف بأمان', 'Too close to stop safely'],
  r_partnerBusy: ['الزميل مشغول: {task}', 'Partner busy: {task}'],
  r_partnerSkill: ['محتاج تدريب للزميل (ترقية)', 'Needs partner training (upgrade)'],
  r_pending: ['في استعلام شغال', 'A query is already running'],
  r_resolved: ['القضية مقفولة', 'Case already resolved'],
  r_notStopped: ['العربية مش واقفة', 'Vehicle is not stationary'],
  r_waitGate: ['استنى البوابة', 'Wait for the gate'],
  r_laneBusy: ['الحارة مش فاضية', 'Lane not clear'],
  r_noPriorityVeh: ['مش عربية طوارئ', 'Not an emergency vehicle'],
  r_leaving: ['العربية ماشية', 'Vehicle is leaving'],

  // gate
  g_closed: ['مقفولة', 'Closed'], g_opening: ['بتفتح', 'Opening'], g_open: ['مفتوحة', 'Open'], g_closing: ['بتقفل', 'Closing'], g_jammed: ['عطلانة', 'Jammed'], g_manual: ['يدوي', 'Manual'],
  g_sensorBlock: ['حساس البوابة شايف عربية — منع القفل', 'Gate sensor occupied — closing prevented'],

  // panel titles
  p_dialogue: ['الحوار', 'Conversation'],
  p_docs: ['فحص الأوراق', 'Document check'],
  p_search: ['تفتيش العربية', 'Vehicle search'],
  p_screen: ['الكشف', 'Screening'],
  p_notebook: ['نوتة القضايا', 'Case notebook'],
  p_resolve: ['قرار القضية', 'Case decision'],
  p_partner: ['مهام الزميل', 'Partner tasks'],
  p_radio: ['اللاسلكي', 'Radio'],
  p_record: ['تسجيل ملاحظة', 'Record observation'],
  close: ['إغلاق', 'Close'],
  back: ['رجوع', 'Back'],
  confirm: ['تأكيد', 'Confirm'],
  cancel: ['إلغاء', 'Cancel'],

  // tone
  tone: ['النبرة', 'Tone'],
  tone_calm: ['هادي', 'Calm'], tone_direct: ['مباشر', 'Direct'], tone_firm: ['حازم', 'Firm'],
  d_driverNotes: ['ملاحظات السواق', 'Driver notes'],
  d_statementRec: ['اتسجلت أقوال', 'Statement recorded'],
  d_noOptions: ['مفيش أسئلة جديدة دلوقتي. جرّب الأوراق أو اللاسلكي.', 'No new questions right now. Try documents or the radio.'],
  d_passenger: ['راكب', 'Passenger'],
  d_you: ['أنت', 'You'],

  // documents
  doc_licence: ['رخصة القيادة', 'Driver licence'],
  doc_reg: ['رخصة المركبة', 'Vehicle licence'],
  doc_id: ['بطاقة الرقم القومي', 'Identity card'],
  doc_observed: ['العربية قدامك', 'Observed vehicle'],
  doc_fict: ['وثيقة خيالية للعبة', 'Fictional game document'],
  f_name: ['الاسم', 'Name'], f_dob: ['تاريخ الميلاد', 'Date of birth'], f_licNo: ['رقم الرخصة', 'Licence no.'],
  f_class: ['الفئة', 'Class'], f_expiry: ['سارية حتى', 'Valid until'], f_plate: ['رقم اللوحة', 'Plate no.'],
  f_make: ['الماركة', 'Make'], f_colour: ['اللون', 'Colour'], f_vclass: ['نوع الترخيص', 'Licence type'],
  f_owner: ['المالك', 'Owner'], f_idNo: ['رقم البطاقة (لعبة)', 'Card no. (game)'], f_address: ['العنوان', 'Address'],
  f_photo: ['الصورة', 'Photo'], f_face: ['وش السواق', "Driver's face"], f_type: ['النوع', 'Type'],
  doc_today: ['تاريخ النهارده: {d}', "Today's date: {d}"],
  doc_select: ['اختار حقلين للمقارنة، أو حقل تاريخ واحد', 'Select two fields to compare, or one date field'],
  doc_record: ['سجّل سبب المخالفة', 'Record the violation'],
  doc_match: ['الحقلين دول متطابقين — مفيش تعارض يتسجل.', 'Those fields match — nothing to record.'],
  doc_notExpired: ['التاريخ ساري — مفيش مشكلة.', 'This date is still valid.'],
  doc_already: ['التعارض ده متسجل قبل كده.', 'That discrepancy is already recorded.'],
  doc_recorded: ['اتسجل في النوتة: {x}', 'Recorded in notebook: {x}'],
  doc_zoom: ['تكبير', 'Enlarge'],
  doc_assist: ['تمييز تلقائي (مساعدة)', 'Auto-highlight (assist)'],
  doc_invalidPair: ['الحقول دي مش بتتقارن ببعض', 'Those fields cannot be compared'],
  doc_expiredOn: ['منتهية من {n} يوم', 'Expired {n} days ago'],

  // radio / verification
  rv_vehicle: ['استعلام عن العربية واللوحة', 'Check vehicle & plate'],
  rv_person: ['استعلام عن الرخصة والسواق', 'Check licence & driver'],
  rv_confirm: ['اطلب تأكيد من المشرف', 'Request supervisor confirmation'],
  rv_sent: ['اتبعت الاستعلام… مستني رد', 'Query sent… awaiting reply'],
  rv_clear: ['سليم', 'Clear'], rv_outdated: ['سجل قديم / اتحدث', 'Outdated record'], rv_unresolved: ['مفيش رد واضح', 'Unresolved'], rv_flagged: ['عليه ملاحظة', 'Flagged'],
  rv_confirmed: ['اتأكد', 'Confirmed'], rv_notConfirmed: ['متأكدش', 'Not confirmed'],
  rv_retry: ['الإشارة ضعيفة — جرّب تاني', 'Weak signal — retry'],

  // notebook types
  nb_statement: ['أقوال', 'Statement'], nb_observation: ['ملاحظة', 'Observation'], nb_discrepancy: ['تعارض', 'Discrepancy'],
  nb_verification: ['استعلام', 'Verification'], nb_evidence: ['حرز', 'Evidence'], nb_screening: ['كشف', 'Screening'],
  nb_incident: ['واقعة', 'Incident'], nb_item: ['غرض', 'Item'],
  nb_unverified: ['غير متحقق', 'Unverified'], nb_verified: ['متحقق', 'Verified'], nb_pending: ['قيد الانتظار', 'Pending'],
  nb_empty: ['النوتة فاضية. كلام السواق، التعارضات ونتايج الاستعلام بتتسجل هنا.', 'Notebook is empty. Statements, discrepancies and verification results appear here.'],
  nb_allCases: ['كل القضايا', 'All cases'],
  nb_thisCase: ['القضية الحالية', 'Current case'],

  // search
  s_zones: ['أماكن التفتيش', 'Search areas'],
  s_reason: ['سبب التفتيش', 'Reason for search'],
  s_reasonPick: ['اختار سبب قبل ما تفتش', 'Choose a reason before searching'],
  s_open: ['افتح الباب', 'Open door'],
  s_openAll: ['افتح', 'Open'],
  s_searching: ['بيفتش… {s}ث', 'Searching… {s}s'],
  s_empty: ['مفيش حاجة تستاهل هنا.', 'Nothing of note here.'],
  s_noArt: ['رسومات داخلية للنوع ده مش موجودة في الحزمة — التفتيش بقايمة أماكن.', 'No interior art for this model in the pack — inspection uses a labelled zone list.'],
  s_items: ['المحتويات', 'Contents'],
  s_select: ['اختار غرض', 'Select an item'],
  i_examine: ['افحص', 'Examine'], i_ask: ['اسأل صاحبه', 'Ask owner'], i_identify: ['تعرّف عليه', 'Identify'],
  i_record: ['سجّل', 'Record'], i_return: ['رجّعه', 'Return'], i_bag: ['تحريز', 'Bag as evidence'],
  i_needGloves: ['محتاج جوانتي وكيس أحراز', 'Needs gloves and an evidence bag'],
  i_bagged: ['متحرز', 'Bagged'], i_returned: ['اترجع', 'Returned'], i_identifying: ['بيتعرف… {s}ث', 'Identifying… {s}s'],
  z_driver: ['مكان السواق', 'Driver area'], z_seats: ['الكراسي', 'Seats'], z_floor: ['الأرضية', 'Floor'], z_luggage: ['الشنط', 'Luggage'],
  z_storage: ['الشنطة الخلفية', 'Rear storage'], z_glovebox: ['التابلوه', 'Glovebox'], z_boot: ['الشنطة', 'Boot'], z_cargo: ['صندوق النقل', 'Cargo bed'], z_cabin: ['الكابينة', 'Cabin'],
  sr_discrepancy: ['تعارض في الأوراق', 'Document discrepancy'], sr_alert: ['استعلام عليه ملاحظة', 'Flagged record'],
  sr_statement: ['أقوال متناقضة', 'Contradicting statements'], sr_consent: ['موافقة السواق', 'Driver consent'],
  sr_observation: ['ملاحظة مباشرة', 'Direct observation'], sr_routine: ['روتيني بدون سبب', 'Routine, no specific reason'],

  // screening
  sc_breath: ['كشف النفس', 'Breath screening'], sc_drug: ['كشف المخدرات المبدئي', 'Preliminary drug screening'],
  sc_explain: ['اشرح للسواق', 'Explain to driver'], sc_selfcheck: ['فحص ذاتي للجهاز', 'Device self-check'],
  sc_mouth: ['ركّب مبسم جديد', 'Fit new mouthpiece'], sc_gloves: ['البس جوانتي', 'Put on gloves'],
  sc_sample: ['خد العينة (اضغط مطولاً)', 'Take sample (hold)'], sc_swab: ['خد مسحة', 'Collect swab'],
  sc_process: ['تحليل', 'Processing'], sc_result: ['النتيجة', 'Result'],
  sc_repeat: ['إعادة العينة', 'Repeat sample'], sc_confirm: ['اطلب تأكيد', 'Request confirmation'], sc_medical: ['اطلب دعم طبي', 'Call medical support'],
  sc_ready: ['الجهاز جاهز', 'Device ready'], sc_fault: ['الجهاز عطلان', 'Equipment unavailable'],
  sc_supplies: ['المستلزمات: مباسم {m} • أطقم كشف {k} • جوانتي {g} • أكياس أحراز {b}', 'Supplies: mouthpieces {m} • kits {k} • gloves {g} • evidence bags {b}'],
  sc_res_clear: ['سليم', 'CLEAR'], sc_res_refer: ['يحتاج تأكيد', 'REFER'], sc_res_invalid: ['عينة غير صالحة', 'INVALID SAMPLE'], sc_res_pending: ['في انتظار التأكيد', 'PENDING CONFIRMATION'], sc_res_unavail: ['الجهاز غير متاح', 'EQUIPMENT UNAVAILABLE'],
  sc_prelim: ['النتيجة المبدئية مش إدانة. لازم تأكيد.', 'A preliminary result is not a finding. Confirmation is required.'],
  sc_holdHint: ['كمّل الضغط لحد ما المؤشر يوصل للآخر', 'Keep holding until the meter fills'],
  sc_tooShort: ['النفس قصير — العينة مش صالحة', 'Breath too short — sample invalid'],
  sc_fictional: ['قواعد لعبة خيالية — مش إرشادات طبية أو قانونية حقيقية.', 'Fictional game rules — not real medical or legal procedure.'],
  sc_noReason: ['مفيش مؤشر مسجل يبرر الكشف — هيتحسب على التناسب', 'No recorded indicator justifies screening — this affects proportionality'],

  // resolution
  res_release: ['خليه يعدي', 'Clear and release'], res_release_f: ['خليها تعدي', 'Clear and release'], res_advice: ['نصيحة', 'Give advice'], res_warning: ['إنذار', 'Issue warning'],
  res_citation: ['مخالفة', 'Record citation'], res_refer_admin: ['إحالة إدارية', 'Administrative referral'],
  res_medical: ['مساعدة طبية', 'Arrange medical help'], res_hold: ['تحفظ لحين التحقق', 'Hold pending verification'],
  res_handover: ['تسليم تحت إشراف', 'Supervised handover'],
  res_reason: ['السبب', 'Reason'], res_support: ['الملاحظات الداعمة', 'Supporting observations'],
  res_needSupport: ['القرار ده محتاج ملاحظة داعمة واحدة على الأقل', 'This decision needs at least one supporting observation'],
  res_needGrounds: ['محتاج استعلام عليه ملاحظة، أو نتيجة كشف، أو حرز', 'Needs a flagged record, screening result or evidence'],
  res_needConfirmed: ['محتاج نتيجة مؤكدة (استعلام أو كشف)', 'Needs a confirmed record or confirmed result'],
  res_needReason: ['اختار سبب', 'Choose a reason'],
  res_known: ['المعروف', 'Known facts'], res_open: ['أسئلة مفتوحة', 'Open questions'],
  res_none: ['مفيش', 'None'],
  res_done: ['اتسجل القرار: {d}', 'Decision recorded: {d}'],
  res_pendingQ: ['في استعلام أو تأكيد لسه مستني', 'A query or confirmation is still pending'],
  res_unreviewedDocs: ['الأوراق مااتراجعتش', 'Documents not reviewed'],
  rr_routine: ['فحص روتيني — كل حاجة سليمة', 'Routine check — everything in order'],
  rr_expired: ['رخصة منتهية (قيادة أو عربية)', 'Expired licence (driving or vehicle)'],
  rr_noLicence: ['مفيش رخصة قيادة سارية معاه', 'No valid driving licence'],
  rr_admin: ['مخالفة في الأوراق (المالك / اللوحة / البيانات)', 'Paperwork violation (owner, plate or details)'],
  rr_alert: ['عليه تعميم أو ملاحظة في الاستعلام', 'Flagged by the radio check'],
  rr_screen: ['نتيجة كشف متأكدة (نفَس أو مخدرات)', 'Confirmed breath or drug result'],
  rr_medical: ['حالة طبية محتاجة إسعاف', 'Medical condition that needs help'],
  rr_safety: ['العربية مش آمنة تمشي على الطريق', 'Vehicle not safe to drive'],
  rr_conduct: ['تصرف أو كلام غير لائق مع الكمين', 'Improper behaviour at the checkpoint'],
  rr_evidence: ['حرز أو دليل متأكد لقيته في العربية', 'Confirmed evidence found in the vehicle'],
  rr_favour: ['عرض رشوة أو خدمة علشان يعدّي', 'Offered a bribe or favour to pass'],
  rr_journey: ['أقواله عن المشوار متناقضة', 'Contradicting story about the trip'],

  // partner
  pt_traffic: ['نظّم المرور عند البوابة', 'Manage traffic at the gate'],
  pt_verify: ['اعمل الاستعلام', 'Run the verification'],
  pt_medical: ['اسعف الحالة', 'Attend the medical case'],
  pt_assist: ['ساعد في التفتيش', 'Assist with the inspection'],
  pt_repair: ['صلّح موتور البوابة', 'Repair the gate motor'],
  pt_generator: ['شغّل المولد', 'Restart the generator'],
  pt_cones: ['افتح/اقفل حارة الطوارئ', 'Open/close the priority lane'],
  pt_supplies: ['هات مستلزمات من البوكس', 'Fetch supplies from the booth'],
  pt_vehicle: ['ساعد العربية العطلانة', 'Help the broken-down vehicle'],
  pt_visitor: ['ساعد الزائر', 'Help the visitor'],
  pt_idle: ['رجّعه مكانه', 'Return to post'],
  pt_replace: ['الزميل مشغول. يسيب المهمة الحالية؟', 'Partner is busy. Replace the current task?'],
  pt_walking: ['ماشي', 'walking'],

  // events
  ev_ambulance: ['إسعاف جاي من الغرب — افتح حارة الطوارئ', 'Ambulance approaching from the west — open the priority lane'],
  ev_ambPassed: ['الإسعاف عدّى', 'Ambulance passed'],
  ev_ambBlocked: ['الإسعاف متعطل عند الأقماع!', 'Ambulance blocked at the cones!'],
  ev_overheat: ['ميكروباص سخن — بخار طالع من الموتور', 'Vehicle overheating — steam from the engine'],
  ev_stall: ['العربية عطلت عند العلامة', 'Vehicle stalled at the marker'],
  ev_collision: ['خبطة خفيفة في الطابور', 'Minor bump in the queue'],
  ev_wedding: ['زفة فرح في الطابور — الناس زهقانة', 'Wedding convoy in the queue — getting impatient'],
  ev_visitor: ['زائر تايه بيسأل على الطريق عند الكشك', 'A lost visitor is asking for directions at the booth'],
  ev_gateFault: ['موتور البوابة عطل', 'Gate motor fault'],
  ev_generator: ['المولد فصل — الإضاءة ضعفت', 'Generator tripped — lighting reduced'],
  ev_radioDelay: ['ضغط على العمليات — الرد أبطأ شوية', 'Dispatch busy — radio replies slightly slower'],
  ev_dust: ['تراب كتير — الرؤية ضعيفة', 'Blowing dust — visibility reduced'],
  ev_medical: ['حالة طبية في عربية في الطابور!', 'Medical emergency in a queued vehicle!'],
  ev_leave: ['عربية بتحاول تمشي قبل الإذن!', 'A vehicle is trying to leave before clearance!'],
  ev_prioAbuse: ['عربية دخلت حارة الطوارئ المفتوحة وعدّت الكمين', 'A vehicle used the open priority lane to skip the check'],
  ev_honk: ['كلاكسات في الطابور', 'Honking in the queue'],
  ev_returning: ['وش مألوف: {n}', 'Familiar face: {n}'],
  ev_resolved: ['اتحلت: {e}', 'Resolved: {e}'],
  ev_supervisor: ['بوكس الشرطة وصل للتسليم', 'Police pickup arrived for handover'],

  // report
  rp_title: ['الوردية خلصت', 'Shift complete'],
  rp_vehicles: ['عربيات اتعاملت معاها', 'Vehicles handled'],
  rp_checked: ['اتفحصت', 'Checked'],
  rp_waved: ['عدّت', 'Waved through'],
  rp_correct: ['قرارات سليمة', 'Sound decisions'],
  rp_wait: ['متوسط الانتظار', 'Average wait'],
  rp_complaints: ['شكاوى', 'Complaints'],
  rp_trust: ['ثقة الناس', 'Community trust'],
  rp_score: ['التقييم', 'Score'],
  rp_decision: ['جودة القرار', 'Decision quality'],
  rp_proportion: ['التناسب', 'Proportionality'],
  rp_safety: ['سلامة المرور', 'Traffic safety'],
  rp_comm: ['التواصل', 'Communication'],
  rp_cases: ['مراجعة القضايا', 'Case review'],
  rp_upgrades: ['تطوير الكمين', 'Station upgrades'],
  rp_credits: ['رصيد التطوير: {n}', 'Upgrade credit: {n}'],
  rp_next: ['الوردية الجاية', 'Next shift'],
  rp_updates: ['تحديثات من العمليات', 'Dispatcher updates'],
  rp_noCases: ['مفيش قضايا اتفحصت', 'No cases were examined'],
  rp_why: ['ليه؟', 'Why?'],
  rp_menu: ['القائمة الرئيسية', 'Main menu'],
  rp_waveNote: ['عدّت بدون فحص', 'Passed without a check'],
  up_lighting: ['إضاءة أفضل', 'Better lighting'], up_lighting_d: ['رؤية أوضح بالليل وأقل أعطال', 'Clearer night view, fewer outages'],
  up_radio: ['لاسلكي أقوى', 'Radio reliability'], up_radio_d: ['ردود أسرع وأقل انقطاع', 'Faster replies, fewer dropouts'],
  up_supplies: ['مستلزمات إضافية', 'Extra supplies'], up_supplies_d: ['مباسم وأطقم وأكياس أحراز أكتر', 'More mouthpieces, kits and bags'],
  up_partner: ['تدريب الزميل', 'Partner training'], up_partner_d: ['مهام جديدة: إسعاف، تفتيش، صيانة', 'New tasks: medical, search, repairs'],
  up_bay: ['ساحة فحص تانية', 'Second inspection bay'], up_bay_d: ['عربيتين في الساحة', 'Two vehicles in the bay'],
  up_buy: ['طوّر ({c})', 'Upgrade ({c})'], up_max: ['أقصى مستوى', 'Maxed'], up_lvl: ['مستوى {n}', 'Level {n}'],
  up_noCredit: ['الرصيد مش كفاية', 'Not enough credit'],

  // briefing / tutorial
  br_title: ['تمام الوردية', 'Shift briefing'],
  br_location: ['الموقع', 'Location'],
  br_unlocks: ['الجديد في الوردية دي', 'New this shift'],
  br_start: ['استلم الوردية', 'Start shift'],
  br_length: ['مدة الوردية: حوالي {n} دقيقة', 'Shift length: about {n} minutes'],
  br_tip: ['معظم الناس عاديين. التعارض سبب للسؤال، مش دليل إدانة.', 'Most people are ordinary. A mismatch is a reason to ask, not proof of guilt.'],
  unl_1: ['المرور والأوراق', 'Traffic and papers'],
  unl_2: ['علاقة السواق بالمالك والاستعلامات', 'Driver/owner relationships and alerts'],
  unl_3: ['تفتيش العربيات', 'Vehicle search'],
  unl_4: ['كشف النفس والمخدرات', 'Breath and drug screening'],
  unl_5: ['مهام الزميل والطوارئ', 'Partner tasks and emergencies'],
  unl_6: ['قضايا مركبة', 'Combined cases'],
  tut_title: ['تدريب', 'Training'],
  tut_skip: ['تخطي التدريب', 'Skip training'],
  tut_1: ['امشي بالظابط: A/D أو الأسهم، أو اضغط على الأرض.', 'Walk the officer: A/D or arrows, or click/tap the ground.'],
  tut_2: ['استنى أول عربية توصل لعلامة الوقوف واضغط عليها.', 'Wait for the first vehicle to reach the stop marker, then select it.'],
  tut_3: ['العربية واقفة عند البوابة — اضغط «فحص» علشان تبدأ تفحصها.', 'The car is waiting at the gate — press “Inspect” to start checking it.'],
  tut_4: ['الظابط راح للشباك — اطلب الرخص: «مساء الخير — الرخص لو سمحت».', 'The officer is at the window — ask for the papers: “Good evening — licences, please”.'],
  tut_5: ['لما السواق يسلّمك الرخص، افتح «الأوراق» وقارن.', 'Once the driver hands them over, open “Documents” and compare.'],
  tut_6: ['لو في حاجة مش واضحة، استعلم باللاسلكي.', 'If something is unclear, verify it on the radio.'],
  tut_7: ['اختار «قرار»، حدد السبب، وبعدين رجّع الأوراق.', 'Choose “Resolve case”, pick a reason, then return the documents.'],
  tut_8: ['العربيات العادية تقدر تعدّيها على طول بـ«عدّي». حافظ على الطابور ماشي.', 'Ordinary vehicles can simply be waved through. Keep the queue moving.'],
  tut_done: ['التدريب خلص. الوردية مستمرة — بالتوفيق.', 'Training complete. The shift continues — good luck.'],

  // settings
  set_title: ['الإعدادات', 'Settings'],
  set_lang: ['اللغة', 'Language'],
  set_shift: ['مدة الوردية', 'Shift length'],
  set_min: ['{n} دقيقة', '{n} min'],
  set_read: ['الوقت أثناء القراءة', 'Time while reading'],
  set_read_slow: ['أبطأ (٠٫٣٥×)', 'Slowed (0.35×)'], set_read_pause: ['متوقف', 'Paused'],
  set_assist: ['تمييز التعارضات تلقائياً', 'Auto-highlight discrepancies'],
  set_subs: ['ترجمة الأصوات', 'Sound captions'],
  set_fx: ['تقليل المؤثرات', 'Reduced effects'],
  set_flash: ['تقليل الوميض', 'Reduced flashing'],
  set_text: ['حجم الخط', 'Text size'],
  set_master: ['الصوت العام', 'Master volume'], set_amb: ['صوت الجو', 'Ambience'], set_sfx: ['المؤثرات', 'Effects'],
  set_mute: ['كتم', 'Mute'],
  set_save: ['الحفظ', 'Saving'],
  set_saveNow: ['احفظ دلوقتي', 'Save now'],
  set_export: ['تصدير نسخة', 'Export backup'],
  set_import: ['استيراد نسخة', 'Import backup'],
  set_importPaste: ['الصق نص النسخة هنا', 'Paste backup text here'],
  set_importDo: ['استرجاع', 'Restore'],
  set_copy: ['انسخ', 'Copy'],
  set_copied: ['اتنسخ', 'Copied'],
  set_on: ['شغال', 'On'], set_off: ['مقفول', 'Off'],
  set_quality: ['الجودة', 'Quality'], set_q_high: ['عالية', 'High'], set_q_low: ['خفيفة', 'Low'],
  set_small: ['صغير', 'Small'], set_normal: ['عادي', 'Normal'], set_large: ['كبير', 'Large'],
  set_perf: ['الأداء', 'Performance'],
  sv_saved: ['اتحفظ', 'Saved'],
  sv_auto: ['حفظ تلقائي', 'Autosaved'],
  sv_fail: ['الحفظ فشل: {e}. صدّر نسخة احتياطية.', 'Save failed: {e}. Export a backup instead.'],
  sv_loadFail: ['تعذر تحميل الحفظ: {e}', 'Could not load save: {e}'],
  sv_badFile: ['الملف مش نسخة صالحة: {e}', 'Not a valid backup: {e}'],
  sv_restored: ['اترجعت النسخة', 'Backup restored'],
  sv_version: ['نسخة حفظ غير مدعومة ({v})', 'Unsupported save version ({v})'],

  pause_title: ['متوقف', 'Paused'],
  pause_resume: ['كمّل', 'Resume'],
  pause_quit: ['احفظ واخرج للقائمة', 'Save and quit to menu'],
  pause_end: ['اختم الوردية دلوقتي', 'End shift now'],

  how_body: ['<p><b>الهدف:</b> حافظ على الطريق ماشي، وافحص اللي يستاهل بشكل متناسب، واتخذ قرارات مبنية على دليل.</p><p><b>الحركة:</b> A/D أو الأسهم، أو اضغط على الطريق. <b>Q/E</b> لاختيار عربية. <b>1–9</b> للأزرار. <b>N</b> النوتة. <b>Esc</b> يقفل. <b>Space</b> إيقاف.</p><p><b>الدورة:</b> اختار العربية عند العلامة ← عدّيها أو اعمل «فحص» ← كلّم السواق واتكلم ← اطلب الأوراق وقارن ← استعلم باللاسلكي ← حوّل للساحة لو محتاج تفتيش أو كشف ← قرار بسبب وملاحظات ← رجّع الأوراق.</p><p>التعارض سبب للسؤال مش دليل. النتيجة المبدئية للكشف مش إدانة. اللبس والشكل والعصبية ملهمش علاقة بالذنب.</p>', '<p><b>Goal:</b> keep the road moving, check what deserves checking — proportionately — and make evidence-based decisions.</p><p><b>Move:</b> A/D or arrows, or click the road. <b>Q/E</b> selects vehicles. <b>1–9</b> press actions. <b>N</b> notebook. <b>Esc</b> closes. <b>Space</b> pauses.</p><p><b>Loop:</b> select the vehicle at the marker → wave through or signal stop → approach and talk → request and compare documents → verify by radio → divert to the bay if a search or screening is justified → decide with a reason and supporting notes → return documents.</p><p>A mismatch is a reason to ask, not proof. A preliminary screening result is not a finding. Clothes, looks and nervousness say nothing about guilt.</p>'],
  missingArt: ['الأصول الناقصة للتوسعات', 'Missing art for expansions'],
});
;(window.CP_FILES = window.CP_FILES || {})['01_strings'] = '2.5.1';
